### ISSUE TITLE
train_cv does not seem to exist

### ISSUE THREAD

**Issue by cao-hong** [alncat/opusDSD#9]
**Describe the bug**

When I submitted the following training code, an unexpected error occurred:

dsd train_cv ./all.mrcs --ctf ./sp-ctf.pkl --poses ./sp-pose-euler.pkl --lazy-single --pe-type vanilla --encode-mode grad --template-type conv -n 20 -b 12 --zdim 12 --lr 1.e-4 --num-gpus 1 --beta-control 2. --beta cos -o /work/sp -r ./mask.mrc --downfrac 0.75 --valfrac 0.25 --lamb 1. --split sp-split.pkl --bfactor 4. --templateres 224

Error:
usage: dsd [-h] [--version]
           {downsample,preprocess,parse_pose_csparc,parse_pose_star,parse_ctf_csparc,parse_ctf_star,train_nn,backproject_voxel,train_vae,eval_vol,eval_images,analyze,analyze_landscape,analyze_landscape_full,pc_traversal,graph_traversal,view_config,abinit_homo,abinit_het}
           ...
dsd: error: argument {downsample,preprocess,parse_pose_csparc,parse_pose_star,parse_ctf_csparc,parse_ctf_star,train_nn,backproject_voxel,train_vae,eval_vol,eval_images,analyze,analyze_landscape,analyze_landscape_full,pc_traversal,graph_traversal,view_config,abinit_homo,abinit_het}: invalid choice: 'train_cv' (choose from 'downsample', 'preprocess', 'parse_pose_csparc', 'parse_pose_star', 'parse_ctf_csparc', 'parse_ctf_star', 'train_nn', 'backproject_voxel', 'train_vae', 'eval_vol', 'eval_images', 'analyze', 'analyze_landscape', 'analyze_landscape_full', 'pc_traversal', 'graph_traversal', 'view_config', 'abinit_homo', 'abinit_het')

train_cv does not seem to exist. I look forward to your reply

**To Reproduce**
What is the command you used?

**Expected behavior**

**Additional context**

**Comment by alncat** [comment]
did you clone the latest repository using ```git pull```, and install the package using ```pip install -e .```
